<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
global $APPLICATION;
$APPLICATION->SetTitle("Сравнение");
?>
	<div class="title title-page">
		<div class="title__text"><?$APPLICATION->ShowTitle()?></div>
		<div class="title__backlink">
			<i class="icon-arrow-left"></i>
			<a href="">вернуться</a>
		</div>
	</div>
<?php
global $arCompareFilter;
$arCompareFilter['ID'] = WorkCart::getCookie('userCompare', true);
if(!$arCompareFilter['ID']){
    $arCompareFilter['ID'] = -1;
    echo 'В сравнении нет товаров!<br><br><br><br><br>';
}

if($arCompareFilter['ID'] != -1){
    $APPLICATION->IncludeComponent(
	"bitrix:catalog.section", 
	"compare", 
	array(
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "15",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER2" => "desc",
		"PROPERTY_CODE" => array(
			0 => "COLOR_HREF",
			1 => "ARTICLE",
			2 => "T_1",
			3 => "T_2",
			4 => "T_3",
			5 => "T_4",
			6 => "T_5",
			7 => "T_6",
			8 => "T_7",
			9 => "T_8",
			10 => "T_9",
			11 => "T_13",
			12 => "T_14",
			13 => "T_18",
			14 => "T_19",
			15 => "T_20",
			16 => "T_22",
			17 => "T_23",
			18 => "T_25",
			19 => "T_28",
			20 => "T_31",
			21 => "T_32",
			22 => "T_33",
			23 => "T_35",
			24 => "T_37",
			25 => "T_38",
			26 => "T_40",
			27 => "T_41",
			28 => "T_42",
			29 => "T_43",
			30 => "T_44",
			31 => "T_45",
			32 => "T_46",
			33 => "T_47",
			34 => "T_48",
			35 => "T_49",
			36 => "T_50",
			37 => "T_51",
			38 => "T_52",
			39 => "T_53",
			40 => "T_54",
			41 => "T_55",
			42 => "T_56",
			43 => "T_57",
			44 => "T_58",
			45 => "T_59",
			46 => "T_60",
			47 => "T_61",
			48 => "T_62",
			49 => "T_63",
			50 => "T_64",
			51 => "T_65",
			52 => "T_66",
			53 => "T_67",
			54 => "T_68",
			55 => "T_69",
			56 => "T_70",
			57 => "T_71",
			58 => "T_72",
			59 => "T_73",
			60 => "T_74",
			61 => "T_75",
			62 => "T_76",
			63 => "T_77",
			64 => "T_78",
			65 => "T_79",
			66 => "T_80",
			67 => "T_81",
			68 => "T_82",
			69 => "T_84",
			70 => "T_85",
			71 => "T_86",
			72 => "T_87",
			73 => "T_88",
			74 => "T_90",
			75 => "T_91",
			76 => "T_92",
			77 => "T_93",
			78 => "T_94",
			79 => "T_95",
			80 => "T_96",
			81 => "T_97",
			82 => "T_118",
			83 => "T_133",
			84 => "T_134",
			85 => "T_135",
			86 => "T_136",
			87 => "T_137",
			88 => "N_1",
			89 => "N_2",
			90 => "N_3",
			91 => "N_4",
			92 => "N_6",
			93 => "N_7",
			94 => "N_8",
			95 => "N_9",
			96 => "N_13",
			97 => "N_14",
			98 => "N_18",
			99 => "N_25",
			100 => "N_28",
			101 => "N_31",
			102 => "N_32",
			103 => "N_37",
			104 => "N_38",
			105 => "N_41",
			106 => "N_42",
			107 => "N_43",
			108 => "N_44",
			109 => "N_51",
			110 => "N_52",
			111 => "N_53",
			112 => "N_54",
			113 => "N_55",
			114 => "N_56",
			115 => "N_57",
			116 => "N_58",
			117 => "N_59",
			118 => "N_60",
			119 => "N_61",
			120 => "N_63",
			121 => "N_64",
			122 => "N_65",
			123 => "N_66",
			124 => "N_67",
			125 => "N_68",
			126 => "N_69",
			127 => "N_70",
			128 => "N_71",
			129 => "N_72",
			130 => "N_73",
			131 => "N_75",
			132 => "N_76",
			133 => "N_77",
			134 => "N_78",
			135 => "N_79",
			136 => "N_80",
			137 => "N_81",
			138 => "N_82",
			139 => "N_84",
			140 => "N_86",
			141 => "N_87",
			142 => "N_88",
			143 => "N_89",
			144 => "N_90",
			145 => "N_91",
			146 => "N_92",
			147 => "N_93",
			148 => "N_96",
			149 => "N_97",
			150 => "N_118",
			151 => "N_133",
			152 => "N_134",
			153 => "N_135",
			154 => "N_136",
			155 => "N_137",
			156 => "MY_5",
			157 => "MY_11",
			158 => "MY_12",
			159 => "MY_12_2",
			160 => "MY_25",
			161 => "MY_50",
			162 => "MY_4_20",
			163 => "",
		),
		"META_KEYWORDS" => "",
		"META_DESCRIPTION" => "",
		"BROWSER_TITLE" => "-",
		"INCLUDE_SUBSECTIONS" => "N",
		"SHOW_ALL_WO_SECTION" => "Y",
		"BASKET_URL" => $arParams["BASKET_URL"],
		"ACTION_VARIABLE" => $arParams["ACTION_VARIABLE"],
		"PRODUCT_ID_VARIABLE" => $arParams["PRODUCT_ID_VARIABLE"],
		"SECTION_ID_VARIABLE" => $arParams["SECTION_ID_VARIABLE"],
		"PRODUCT_QUANTITY_VARIABLE" => $arParams["PRODUCT_QUANTITY_VARIABLE"],
		"PRODUCT_PROPS_VARIABLE" => $arParams["PRODUCT_PROPS_VARIABLE"],
		"FILTER_NAME" => "arCompareFilter",
		"USE_FILTER" => "Y",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => $arParams["CACHE_TIME"],
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "N",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "N",
		"DISPLAY_COMPARE" => "N",
		"PAGE_ELEMENT_COUNT" => "100",
		"LINE_ELEMENT_COUNT" => "1",
		"PRICE_CODE" => array(
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => $arParams["SHOW_PRICE_COUNT"],
		"PRICE_VAT_INCLUDE" => "Y",
		"USE_PRODUCT_QUANTITY" => "Y",
		"PRODUCT_PROPERTIES" => array(
		),
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => $arParams["PAGER_TITLE"],
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => $arParams["PAGER_TEMPLATE"],
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => $arParams["PAGER_DESC_NUMBERING_CACHE_TIME"],
		"PAGER_SHOW_ALL" => "N",
		"OFFERS_CART_PROPERTIES" => $arParams["OFFERS_CART_PROPERTIES"],
		"OFFERS_FIELD_CODE" => $arParams["LIST_OFFERS_FIELD_CODE"],
		"OFFERS_PROPERTY_CODE" => $arParams["LIST_OFFERS_PROPERTY_CODE"],
		"OFFERS_SORT_FIELD" => $arParams["OFFERS_SORT_FIELD"],
		"OFFERS_SORT_ORDER" => $arParams["OFFERS_SORT_ORDER"],
		"OFFERS_SORT_FIELD2" => $arParams["OFFERS_SORT_FIELD2"],
		"OFFERS_SORT_ORDER2" => $arParams["OFFERS_SORT_ORDER2"],
		"OFFERS_LIMIT" => $arParams["LIST_OFFERS_LIMIT"],
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"SECTION_URL" => SITE_DIR."catalog/#SECTION_CODE#/",
		"DETAIL_URL" => SITE_DIR."catalog/product/#ELEMENT_CODE#/",
		"CONVERT_CURRENCY" => "N",
		"CURRENCY_ID" => $arParams["CURRENCY_ID"],
		"HIDE_NOT_AVAILABLE" => "N",
		"LABEL_PROP" => "",
		"ADD_PICT_PROP" => "-",
		"PRODUCT_DISPLAY_MODE" => $arParams["PRODUCT_DISPLAY_MODE"],
		"OFFER_ADD_PICT_PROP" => $arParams["OFFER_ADD_PICT_PROP"],
		"OFFER_TREE_PROPS" => $arParams["OFFER_TREE_PROPS"],
		"PRODUCT_SUBSCRIPTION" => "N",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_OLD_PRICE" => "N",
		"MESS_BTN_BUY" => $arParams["MESS_BTN_BUY"],
		"MESS_BTN_ADD_TO_BASKET" => $arParams["MESS_BTN_ADD_TO_BASKET"],
		"MESS_BTN_SUBSCRIBE" => $arParams["MESS_BTN_SUBSCRIBE"],
		"MESS_BTN_DETAIL" => $arParams["MESS_BTN_DETAIL"],
		"MESS_NOT_AVAILABLE" => $arParams["MESS_NOT_AVAILABLE"],
		"TEMPLATE_THEME" => (isset($arParams["TEMPLATE_THEME"])?$arParams["TEMPLATE_THEME"]:""),
		"SECTION_USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"SET_META_KEYWORDS" => "Y",
		"SET_META_DESCRIPTION" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"COMPONENT_TEMPLATE" => "compare",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"BACKGROUND_IMAGE" => "-",
		"PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false}]",
		"ENLARGE_PRODUCT" => "STRICT",
		"PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons",
		"SHOW_SLIDER" => "Y",
		"SHOW_MAX_QUANTITY" => "N",
		"SHOW_CLOSE_POPUP" => "N",
		"RCM_TYPE" => "personal",
		"RCM_PROD_ID" => $_REQUEST["PRODUCT_ID"],
		"SHOW_FROM_SECTION" => "N",
		"SEF_MODE" => "N",
		"SET_BROWSER_TITLE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"ADD_TO_BASKET_ACTION" => "ADD",
		"USE_ENHANCED_ECOMMERCE" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"LAZY_LOAD" => "N",
		"LOAD_ON_SCROLL" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"COMPATIBLE_MODE" => "Y",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"SLIDER_INTERVAL" => "3000",
		"SLIDER_PROGRESS" => "N",
		"PROPERTY_CODE_MOBILE" => "",
		"LABEL_PROP_MOBILE" => "",
		"LABEL_PROP_POSITION" => "top-left"
	),
	false
);
}


?>


<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>